/* Generated by Yosys 0.7+169 (git sha1 3bbac5c, clang 3.4-1ubuntu3 -fPIC -Os) */

(* src = "mydesign.v:3" *)
module simple_design1(a, b, c, d, y);
  wire _0_;
  wire _1_;
  (* src = "mydesign.v:4" *)
  input a;
  (* src = "mydesign.v:4" *)
  input b;
  (* src = "mydesign.v:4" *)
  input c;
  (* src = "mydesign.v:4" *)
  input d;
  (* src = "mydesign.v:5" *)
  output y;
  NAND2X1 _2_ (
    .A(a),
    .B(b),
    .Y(_0_)
  );
  NAND2X1 _3_ (
    .A(c),
    .B(d),
    .Y(_1_)
  );
  XOR2X1 _4_ (
    .A(_0_),
    .B(_1_),
    .Y(y)
  );
endmodule
