/* Generated by Yosys 0.7+169 (git sha1 3bbac5c, clang 3.4-1ubuntu3 -fPIC -Os) */

(* src = "mydesign.v:3" *)
module simple_design1(clk, data, y);
  (* src = "mydesign.v:4" *)
  input clk;
  (* src = "mydesign.v:4" *)
  input data;
  (* src = "mydesign.v:5" *)
  wire q;
  (* src = "mydesign.v:6" *)
  output y;
  OR2X1 _0_ (
    .A(q),
    .B(data),
    .Y(y)
  );
  DFFPOSX1 _1_ (
    .CLK(clk),
    .D(data),
    .Q(q)
  );
endmodule
