/* Generated by Yosys 0.7+169 (git sha1 3bbac5c, clang 3.4-1ubuntu3 -fPIC -Os) */

(* src = "mydesign.v:3" *)
module simple_design1(clk, data, y);
  (* src = "mydesign.v:8" *)
  wire _0_;
  (* src = "mydesign.v:4" *)
  input clk;
  (* src = "mydesign.v:4" *)
  input data;
  (* src = "mydesign.v:5" *)
  wire q1;
  (* src = "mydesign.v:5" *)
  wire q2;
  (* src = "mydesign.v:6" *)
  output y;
  INVX1 _1_ (
    .A(q1),
    .Y(_0_)
  );
  AND2X1 _2_ (
    .A(q2),
    .B(data),
    .Y(y)
  );
  DFFPOSX1 _3_ (
    .CLK(clk),
    .D(data),
    .Q(q1)
  );
  DFFPOSX1 _4_ (
    .CLK(clk),
    .D(_0_),
    .Q(q2)
  );
endmodule
