/* Generated by Yosys 0.7+169 (git sha1 3bbac5c, clang 3.4-1ubuntu3 -fPIC -Os) */

(* src = "mydesign.v:3" *)
module simple_design1(a, b, y);
  (* src = "mydesign.v:4" *)
  input a;
  (* src = "mydesign.v:4" *)
  input b;
  (* src = "mydesign.v:5" *)
  output y;
  AND2X1 _0_ (
    .A(a),
    .B(b),
    .Y(y)
  );
endmodule
