/* Generated by Yosys 0.7+169 (git sha1 3bbac5c, clang 3.4-1ubuntu3 -fPIC -Os) */

(* src = "mydesign.v:3" *)
module simple_design1(a, b, y, sel);
  wire _0_;
  wire _1_;
  (* src = "mydesign.v:4" *)
  input a;
  (* src = "mydesign.v:4" *)
  input b;
  (* src = "mydesign.v:4" *)
  input sel;
  (* src = "mydesign.v:5" *)
  output y;
  INVX1 _2_ (
    .A(a),
    .Y(_0_)
  );
  NAND2X1 _3_ (
    .A(b),
    .B(sel),
    .Y(_1_)
  );
  OAI21X1 _4_ (
    .A(_0_),
    .B(sel),
    .C(_1_),
    .Y(y)
  );
endmodule
